services:
  app:
    container_name: app
    build:
      context: ./app/
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
      - /app/node_modules
    env_file:
      .env
